### ISSUE TITLE
rhino3dm library google app engine deploy(for python,flask) error 

### ISSUE THREAD

**Issue by UgurOzcanFited** [mcneel/rhino3dm#395]
Dear rhino3dm developers, when I tried to deploy to google cloud I got the this error. What can I solve this problem?

```
Step #1:   Building wheel for pycountry (setup.py): started
Step #1:   Building wheel for pycountry (setup.py): finished with status 'done'
Step #1:   Created wheel for pycountry: filename=pycountry-19.8.18-py2.py3-none-any.whl size=10627359 sha256=65d09fc115602b58ccc81b78ad2a26ec959f96d88de2163175fca07fb29917c4
Step #1:   Stored in directory: /root/.cache/pip/wheels/00/77/65/5f318c3c30b046b450a385ecfc690125f8a270cdb0f3f483b4
Step #1:   Building wheel for pyyaml (setup.py): started
Step #1:   Building wheel for pyyaml (setup.py): finished with status 'done'
Step #1:   Created wheel for pyyaml: filename=PyYAML-5.3.1-cp37-cp37m-linux_x86_64.whl size=44619 sha256=3fdabe9b2bce00957c7f58d1b5cb1e83c9f79abe2f617a648604f6a175f646f6
Step #1:   Stored in directory: /root/.cache/pip/wheels/5e/03/1e/e1e954795d6f35dfc7b637fe2277bff021303bd9570ecea653
Step #1:   Building wheel for rhino3dm (setup.py): started
Step #1:   Building wheel for rhino3dm (setup.py): finished with status 'error'
Step #1:   ERROR: Command errored out with exit status 1:
Step #1:    command: /env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-09kvhjg7/rhino3dm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-09kvhjg7/rhino3dm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ciwihizt
Step #1:        cwd: /tmp/pip-install-09kvhjg7/rhino3dm/
Step #1:   Complete output (61 lines):
Step #1:   running bdist_wheel
Step #1:   running build
Step #1:   running build_py
Step #1:   creating build
Step #1:   creating build/lib.linux-x86_64-3.7
Step #1:   creating build/lib.linux-x86_64-3.7/rhino3dm
Step #1:   copying src/rhino3dm/__init__.py -> build/lib.linux-x86_64-3.7/rhino3dm
Step #1:   running egg_info
Step #1:   writing src/rhino3dm.egg-info/PKG-INFO
Step #1:   writing dependency_links to src/rhino3dm.egg-info/dependency_links.txt
Step #1:   writing top-level names to src/rhino3dm.egg-info/top_level.txt
Step #1:   reading manifest file 'src/rhino3dm.egg-info/SOURCES.txt'
Step #1:   reading manifest template 'MANIFEST.in'
Step #1:   warning: no files found matching '*.pyd' under directory 'src/rhino3dm'
Step #1:   warning: no files found matching '*.so' under directory 'src/rhino3dm'
Step #1:   writing manifest file 'src/rhino3dm.egg-info/SOURCES.txt'
Step #1:   copying src/rhino3dm/__init__.pyi -> build/lib.linux-x86_64-3.7/rhino3dm
Step #1:   copying src/rhino3dm/py.typed -> build/lib.linux-x86_64-3.7/rhino3dm
Step #1:   running build_ext
Step #1:   Traceback (most recent call last):
Step #1:     File "/tmp/pip-install-09kvhjg7/rhino3dm/setup.py", line 32, in run
Step #1:       out = subprocess.check_output(['cmake', '--version'])
Step #1:     File "/opt/python3.7/lib/python3.7/subprocess.py", line 411, in check_output
Step #1:       **kwargs).stdout
Step #1:     File "/opt/python3.7/lib/python3.7/subprocess.py", line 488, in run
Step #1:       with Popen(*popenargs, **kwargs) as process:
Step #1:     File "/opt/python3.7/lib/python3.7/subprocess.py", line 800, in __init__
Step #1:       restore_signals, start_new_session)
Step #1:     File "/opt/python3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
Step #1:       raise child_exception_type(errno_num, err_msg, err_filename)
Step #1:   FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
Step #1:   
Step #1:   During handling of the above exception, another exception occurred:
Step #1:   
Step #1:   Traceback (most recent call last):
Step #1:     File "<string>", line 1, in <module>
Step #1:     File "/tmp/pip-install-09kvhjg7/rhino3dm/setup.py", line 150, in <module>
Step #1:       include_package_data=True
Step #1:     File "/env/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
Step #1:       return distutils.core.setup(**attrs)
Step #1:     File "/opt/python3.7/lib/python3.7/distutils/core.py", line 148, in setup
Step #1:       dist.run_commands()
Step #1:     File "/opt/python3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
Step #1:       self.run_command(cmd)
Step #1:     File "/opt/python3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
Step #1:       cmd_obj.run()
Step #1:     File "/env/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 290, in run
Step #1:       self.run_command('build')
Step #1:     File "/opt/python3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
Step #1:       self.distribution.run_command(command)
Step #1:     File "/opt/python3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
Step #1:       cmd_obj.run()
Step #1:     File "/opt/python3.7/lib/python3.7/distutils/command/build.py", line 135, in run
Step #1:       self.run_command(cmd_name)
Step #1:     File "/opt/python3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
Step #1:       self.distribution.run_command(command)
Step #1:     File "/opt/python3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
Step #1:       cmd_obj.run()
Step #1:     File "/tmp/pip-install-09kvhjg7/rhino3dm/setup.py", line 36, in run
Step #1:       ", ".join(e.name for e in self.extensions))
Step #1:   RuntimeError: CMake must be installed to build the following extensions: rhino3dm._rhino3dm
Step #1:   ----------------------------------------
Step #1:   ERROR: Failed building wheel for rhino3dm
Step #1:   Running setup.py clean for rhino3dm
Step #1:   Building wheel for simplejson (setup.py): started
Step #1:   Building wheel for simplejson (setup.py): finished with status 'done'
Step #1:   Created wheel for simplejson: filename=simplejson-3.17.0-cp37-cp37m-linux_x86_64.whl size=117521 sha256=61adb8c3eefd215654a144c8da4abee1814a9d4be6adf14aaafefd41a4247de6
Step #1:   Stored in directory: /root/.cache/pip/wheels/8a/2d/bb/65cfe3f590a9cbb199f2011a6e4ccecd858844fb04e0dee2e9
Step #1:   Building wheel for wrapt (setup.py): started
Step #1:   Building wheel for wrapt (setup.py): finished with status 'done'
Step #1:   Created wheel for wrapt: filename=wrapt-1.12.1-cp37-cp37m-linux_x86_64.whl size=66406 sha256=0a0e96a176b26211a988987e821bae54ceaf8f8ef9d850b83fd6760be24f6b94
Step #1:   Stored in directory: /root/.cache/pip/wheels/62/76/4c/aa25851149f3f6d9785f6c869387ad82b3fd37582fa8147ac6
Step #1: Successfully built compute-rhino3d dill distlib flask-script future gapic-google-cloud-datastore-v1 gapic-google-cloud-logging-v2 googleapis-common-protos identity-toolkit-python-client oauth2client ply proto-google-cloud-datastore-v1 proto-google-cloud-logging-v2 pycountry pyyaml simplejson wrapt
Step #1: Failed to build rhino3dm
Step #1: DEPRECATION: Could not build wheels for rhino3dm which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Step #1: Installing collected packages: pip, chardet, attrs, multidict, idna, yarl, async-timeout, aiohttp, appdirs, asn1crypto, cachetools, certifi, pycparser, cffi, click, urllib3, requests, rhino3dm, compute-rhino3d, coverage, six, cryptography, dill, distlib, entrypoints, enum34, filelock, pycodestyle, mccabe, pyflakes, flake8, markupsafe, jinja2, itsdangerous, werkzeug, flask, flask-script, future, ply, pyasn1, pyasn1-modules, rsa, google-auth, protobuf, googleapis-common-protos, grpcio, google-gax, httplib2, oauth2client, proto-google-cloud-datastore-v1, gapic-google-cloud-datastore-v1, proto-google-cloud-logging-v2, gapic-google-cloud-logging-v2, pytz, google-api-core, uritemplate, google-auth-httplib2, google-api-python-client, google-cloud-core, google-cloud-datastore, google-cloud-logging, google-resumable-media, google-cloud-storage, gunicorn, pyopenssl, simplejson, identity-toolkit-python-client, zipp, importlib-metadata, mako, marshmallow, marshmallow-jsonapi, more-itertools, numpy, opencv-python, pyparsing, packaging, pep8, pillow, pluggy, py, pycountry, pyyaml, pydrive, wcwidth, pytest, python-editor, selenium, slackclient, virtualenv, wheel, wrapt
Step #1:   Attempting uninstall: pip
Step #1:     Found existing installation: pip 20.2.2
Step #1:     Uninstalling pip-20.2.2:
Step #1:       Successfully uninstalled pip-20.2.2
Step #1:     Running setup.py install for rhino3dm: started
Step #1:     Running setup.py install for rhino3dm: finished with status 'error'
Step #1:     ERROR: Command errored out with exit status 1:
Step #1:      command: /env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-09kvhjg7/rhino3dm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-09kvhjg7/rhino3dm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-urxawsbk/install-record.txt --single-version-externally-managed --compile --install-headers /env/include/site/python3.7/rhino3dm
Step #1:          cwd: /tmp/pip-install-09kvhjg7/rhino3dm/
Step #1:     Complete output (63 lines):
Step #1:     running install
Step #1:     running build
Step #1:     running build_py
Step #1:     creating build
Step #1:     creating build/lib.linux-x86_64-3.7
Step #1:     creating build/lib.linux-x86_64-3.7/rhino3dm
Step #1:     copying src/rhino3dm/__init__.py -> build/lib.linux-x86_64-3.7/rhino3dm
Step #1:     running egg_info
Step #1:     writing src/rhino3dm.egg-info/PKG-INFO
Step #1:     writing dependency_links to src/rhino3dm.egg-info/dependency_links.txt
Step #1:     writing top-level names to src/rhino3dm.egg-info/top_level.txt
Step #1:     reading manifest file 'src/rhino3dm.egg-info/SOURCES.txt'
Step #1:     reading manifest template 'MANIFEST.in'
Step #1:     warning: no files found matching '*.pyd' under directory 'src/rhino3dm'
Step #1:     warning: no files found matching '*.so' under directory 'src/rhino3dm'
Step #1:     writing manifest file 'src/rhino3dm.egg-info/SOURCES.txt'
Step #1:     copying src/rhino3dm/__init__.pyi -> build/lib.linux-x86_64-3.7/rhino3dm
Step #1:     copying src/rhino3dm/py.typed -> build/lib.linux-x86_64-3.7/rhino3dm
Step #1:     running build_ext
Step #1:     Traceback (most recent call last):
Step #1:       File "/tmp/pip-install-09kvhjg7/rhino3dm/setup.py", line 32, in run
Step #1:         out = subprocess.check_output(['cmake', '--version'])
Step #1:       File "/opt/python3.7/lib/python3.7/subprocess.py", line 411, in check_output
Step #1:         **kwargs).stdout
Step #1:       File "/opt/python3.7/lib/python3.7/subprocess.py", line 488, in run
Step #1:         with Popen(*popenargs, **kwargs) as process:
Step #1:       File "/opt/python3.7/lib/python3.7/subprocess.py", line 800, in __init__
Step #1:         restore_signals, start_new_session)
Step #1:       File "/opt/python3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
Step #1:         raise child_exception_type(errno_num, err_msg, err_filename)
Step #1:     FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
Step #1:     
Step #1:     During handling of the above exception, another exception occurred:
Step #1:     
Step #1:     Traceback (most recent call last):
Step #1:       File "<string>", line 1, in <module>
Step #1:       File "/tmp/pip-install-09kvhjg7/rhino3dm/setup.py", line 150, in <module>
Step #1:         include_package_data=True
Step #1:       File "/env/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
Step #1:         return distutils.core.setup(**attrs)
Step #1:       File "/opt/python3.7/lib/python3.7/distutils/core.py", line 148, in setup
Step #1:         dist.run_commands()
Step #1:       File "/opt/python3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
Step #1:         self.run_command(cmd)
Step #1:       File "/opt/python3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
Step #1:         cmd_obj.run()
Step #1:       File "/env/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
Step #1:         return orig.install.run(self)
Step #1:       File "/opt/python3.7/lib/python3.7/distutils/command/install.py", line 545, in run
Step #1:         self.run_command('build')
Step #1:       File "/opt/python3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
Step #1:         self.distribution.run_command(command)
Step #1:       File "/opt/python3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
Step #1:         cmd_obj.run()
Step #1:       File "/opt/python3.7/lib/python3.7/distutils/command/build.py", line 135, in run
Step #1:         self.run_command(cmd_name)
Step #1:       File "/opt/python3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
Step #1:         self.distribution.run_command(command)
Step #1:       File "/opt/python3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
Step #1:         cmd_obj.run()
Step #1:       File "/tmp/pip-install-09kvhjg7/rhino3dm/setup.py", line 36, in run
Step #1:         ", ".join(e.name for e in self.extensions))
Step #1:     RuntimeError: CMake must be installed to build the following extensions: rhino3dm._rhino3dm
Step #1:     ----------------------------------------
Step #1: ERROR: Command errored out with exit status 1: /env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-09kvhjg7/rhino3dm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-09kvhjg7/rhino3dm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-urxawsbk/install-record.txt --single-version-externally-managed --compile --install-headers /env/include/site/python3.7/rhino3dm Check the logs for full command output.
Step #1: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
Finished Step #1
ERROR

```

**Comment by sbaer** [comment]
Can you update your python version to 3.8 or 3.9 on app engine? We publish pre-built binaries of rhino3dm to these versions for linux.

Otherwise, you will need to figure out how to install cmake on the app engine deployment as that is what is the problem described in the error message above.
