### ISSUE TITLE
Error install via pip on Arch-Linux python 3.11

### ISSUE THREAD

**Issue by fleixi** [mcneel/rhino3dm#558]
I trying to install rhino3dm via pip and get this error on  Arch-Linux python 3.11

`LANG=C pip install --no-cache-dir  --break-system-packages --user rhino3dm
Collecting rhino3dm
  Downloading rhino3dm-7.14.2.tar.gz (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 3.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: rhino3dm
  Building wheel for rhino3dm (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [125 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/rhino3dm
      copying src/rhino3dm/__init__.py -> build/lib.linux-x86_64-cpython-311/rhino3dm
      running egg_info
      writing src/rhino3dm.egg-info/PKG-INFO
      writing dependency_links to src/rhino3dm.egg-info/dependency_links.txt
      writing top-level names to src/rhino3dm.egg-info/top_level.txt
      reading manifest file 'src/rhino3dm.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.pyd' under directory 'src/rhino3dm'
      warning: no files found matching '*.so' under directory 'src/rhino3dm'
      adding license file 'LICENSE'
      writing manifest file 'src/rhino3dm.egg-info/SOURCES.txt'
      copying src/rhino3dm/__init__.pyi -> build/lib.linux-x86_64-cpython-311/rhino3dm
      copying src/rhino3dm/py.typed -> build/lib.linux-x86_64-cpython-311/rhino3dm
      running build_ext
      extdir = /tmp/pip-install-iruodlia/rhino3dm_77a5fee3f8a14d2a8ce4198da6b2ceba/build/lib.linux-x86_64-cpython-311/rhino3dm
      sourcedir/tmp/pip-install-iruodlia/rhino3dm_77a5fee3f8a14d2a8ce4198da6b2ceba
      -- The C compiler identification is GNU 13.2.1
      -- The CXX compiler identification is GNU 13.2.1
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      Python Compile
      CMake Deprecation Warning at lib/pybind11/CMakeLists.txt:8 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      -- pybind11 v2.9.1
      CMake Warning (dev) at lib/pybind11/tools/FindPythonLibsNew.cmake:98 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.
      
      Call Stack (most recent call first):
        lib/pybind11/tools/pybind11Tools.cmake:50 (find_package)
        lib/pybind11/tools/pybind11Common.cmake:206 (include)
        lib/pybind11/CMakeLists.txt:200 (include)
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Found PythonInterp: /usr/bin/python (found version "3.11.3")
      -- Found PythonLibs: /usr/lib/libpython3.11.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Configuring done (0.4s)
      -- Generating done (0.0s)
      -- Build files have been written to: /tmp/pip-install-iruodlia/rhino3dm_77a5fee3f8a14d2a8ce4198da6b2ceba/build/temp.linux-x86_64-cpython-311
      [  0%] Building CXX object CMakeFiles/_rhino3dm.dir/bindings/base64.cpp.o
      [  0%] Building CXX object CMakeFiles/_rhino3dm.dir/bindings/bindings.cpp.o
      In file included from /tmp/pip-install-iruodlia/rhino3dm_77a5fee3f8a14d2a8ce4198da6b2ceba/src/lib/pybind11/include/pybind11/cast.h:16,
                       from /tmp/pip-install-iruodlia/rhino3dm_77a5fee3f8a14d2a8ce4198da6b2ceba/src/lib/pybind11/include/pybind11/attr.h:13,
                       from /tmp/pip-install-iruodlia/rhino3dm_77a5fee3f8a14d2a8ce4198da6b2ceba/src/lib/pybind11/include/pybind11/pybind11.h:13,
                       from /tmp/pip-install-iruodlia/rhino3dm_77a5fee3f8a14d2a8ce4198da6b2ceba/src/bindings/bindings.h:15,
                       from /tmp/pip-install-iruodlia/rhino3dm_77a5fee3f8a14d2a8ce4198da6b2ceba/src/bindings/bindings.cpp:1:
      /tmp/pip-install-iruodlia/rhino3dm_77a5fee3f8a14d2a8ce4198da6b2ceba/src/lib/pybind11/include/pybind11/detail/type_caster_base.h: In function ‘std::string pybind11::detail::error_string()’:
      /tmp/pip-install-iruodlia/rhino3dm_77a5fee3f8a14d2a8ce4198da6b2ceba/src/lib/pybind11/include/pybind11/detail/type_caster_base.h:482:26: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
        482 |             frame = frame->f_back;
            |                          ^~
      In file included from /usr/include/python3.11/Python.h:42,
                       from /tmp/pip-install-iruodlia/rhino3dm_77a5fee3f8a14d2a8ce4198da6b2ceba/src/lib/pybind11/include/pybind11/detail/common.h:215,
                       from /tmp/pip-install-iruodlia/rhino3dm_77a5fee3f8a14d2a8ce4198da6b2ceba/src/lib/pybind11/include/pybind11/pytypes.h:12,
                       from /tmp/pip-install-iruodlia/rhino3dm_77a5fee3f8a14d2a8ce4198da6b2ceba/src/lib/pybind11/include/pybind11/cast.h:13:
      /usr/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
         22 | typedef struct _frame PyFrameObject;
            |                ^~~~~~
      make[2]: *** [CMakeFiles/_rhino3dm.dir/build.make:90: CMakeFiles/_rhino3dm.dir/bindings/bindings.cpp.o] Error 1
      make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/_rhino3dm.dir/all] Error 2
      make: *** [Makefile:91: all] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-iruodlia/rhino3dm_77a5fee3f8a14d2a8ce4198da6b2ceba/setup.py", line 111, in <module>
          setup(
        File "/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-iruodlia/rhino3dm_77a5fee3f8a14d2a8ce4198da6b2ceba/setup.py", line 45, in run
          self.build_extension(ext)
        File "/tmp/pip-install-iruodlia/rhino3dm_77a5fee3f8a14d2a8ce4198da6b2ceba/setup.py", line 99, in build_extension
          system("make")
        File "/tmp/pip-install-iruodlia/rhino3dm_77a5fee3f8a14d2a8ce4198da6b2ceba/setup.py", line 20, in system
          raise RuntimeError('The command "{}" exited with {}'.format(cmd, rc))
      RuntimeError: The command "make" exited with 2
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for rhino3dm
  Running setup.py clean for rhino3dm
Failed to build rhino3dm
ERROR: Could not build wheels for rhino3dm, which is required to install pyproject.toml-based projects
`

**Comment by fraguada** [comment]
We've updated pybind11 in the dev branch because it was not working with python 3.11. [See this issue](https://github.com/pybind/pybind11/discussions/4333) for another example of changes in python 3.11 that break pybind.

My recommendation is to grab the source dist, for example [from here](https://github.com/mcneel/rhino3dm/suites/15018057666/artifacts/857438536), and see if that builds for your system. 

There will be a release of rhino3dm 8.0.0b2 very soon.
