### ISSUE TITLE
ERROR: Failed building wheel for rhino3dm

### ISSUE THREAD

**Issue by av1dm** [mcneel/rhino3dm#566]
Hello,

I have issues with installing `rhino3dm`. I can install version 8.0.0b2 without any problems. But I need still the actual release.
Can anyone help?

Versions:

- Python: 3.11.4
- pip: 23.2.1
- CMake: 3.27.5 (installed by pip)

Installation output:

```
U:\> pip install rhino3dm==7.14.2
Defaulting to user installation because normal site-packages is not writeable
Collecting rhino3dm==7.14.2
  Using cached rhino3dm-7.14.2.tar.gz (5.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: rhino3dm
  Building wheel for rhino3dm (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for rhino3dm (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [81 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\rhino3dm
      copying src\rhino3dm\__init__.py -> build\lib.win-amd64-cpython-311\rhino3dm
      running egg_info
      writing src\rhino3dm.egg-info\PKG-INFO
      writing dependency_links to src\rhino3dm.egg-info\dependency_links.txt
      writing top-level names to src\rhino3dm.egg-info\top_level.txt
      reading manifest file 'src\rhino3dm.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.pyd' under directory 'src\rhino3dm'
      warning: no files found matching '*.so' under directory 'src\rhino3dm'
      adding license file 'LICENSE'
      writing manifest file 'src\rhino3dm.egg-info\SOURCES.txt'
      copying src\rhino3dm\__init__.pyi -> build\lib.win-amd64-cpython-311\rhino3dm
      copying src\rhino3dm\py.typed -> build\lib.win-amd64-cpython-311\rhino3dm
      running build_ext
      Traceback (most recent call last):
        File "<frozen runpy>", line 198, in _run_module_as_main
        File "<frozen runpy>", line 88, in _run_code
        File "C:\Users\user\AppData\Roaming\Python\Python311\Scripts\cmake.exe\__main__.py", line 4, in <module>
      ModuleNotFoundError: No module named 'cmake'
      Traceback (most recent call last):
        File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\setuptools\build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\setuptools\build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 111, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-idmes3wm\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 32, in run
        File "C:\Program Files\Python311\Lib\subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python311\Lib\subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for rhino3dm
Failed to build rhino3dm
ERROR: Could not build wheels for rhino3dm, which is required to install pyproject.toml-based projects
```

**Comment by fraguada** [comment]
rhino3dm 7.14.2 was built with an older release of pybynd11 which does not support python 3.11. We've updated pybind11, and 8.0.0b2 is built with that and thus installs and runs on your system with python 3.11. If you really need rhino3dm 7.14.2, you's need to downgrade your python install to at least 3.10.
